name: oidc_module
description: Reusable OIDC Module
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  js: ^0.6.7
  openid_client: ^0.4.8
